# Generated by Django 5.1.15 on 2026-09-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='快递单号')),
                ('company', models.CharField(blank=True, default='', max_length=40, verbose_name='快递公司')),
                ('tenant_name', models.CharField(max_length=40, verbose_name='租客姓名')),
                ('tenant_phone', models.CharField(max_length=20, verbose_name='租客手机号')),
                ('building', models.CharField(blank=True, default='', max_length=40, verbose_name='楼栋')),
                ('room_no', models.CharField(blank=True, default='', max_length=20, verbose_name='房号')),
                ('status', models.CharField(choices=[('待入库', '待入库'), ('待取件', '待取件'), ('已取件', '已取件')], default='待入库', max_length=10, verbose_name='状态')),
                ('pickup_code', models.CharField(blank=True, db_index=True, default='', max_length=16, verbose_name='取件凭证')),
                ('operator', models.CharField(blank=True, default='', max_length=40, verbose_name='入库经办人')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('stored_at', models.DateTimeField(blank=True, null=True, verbose_name='入库时间')),
                ('picked_at', models.DateTimeField(blank=True, null=True, verbose_name='取件时间')),
            ],
            options={
                'verbose_name': '快递代收单',
                'ordering': ['-id'],
            },
        ),
    ]
