# 业务错误码统一维护
PROPERTY_NOT_FOUND = 'PROPERTY_NOT_FOUND'
BOOKING_CONFLICT = 'BOOKING_CONFLICT'
REPAIR_INVALID = 'REPAIR_INVALID'

# 参数类
PARAM_REQUIRED = 'PARAM_REQUIRED'

# 快递代收模块
PACKAGE_NOT_FOUND = 'PACKAGE_NOT_FOUND'          # 单号查不到
PACKAGE_DUPLICATE = 'PACKAGE_DUPLICATE'          # 单号已登记
PACKAGE_ALREADY_PICKED = 'PACKAGE_ALREADY_PICKED'  # 重复取件
PACKAGE_STATUS_INVALID = 'PACKAGE_STATUS_INVALID'  # 当前状态不允许该操作
INVALID_PICKUP_CODE = 'INVALID_PICKUP_CODE'      # 取件凭证不符

# 兼容旧引用
ERROR_CODES = {
    'PROPERTY_NOT_FOUND': PROPERTY_NOT_FOUND,
    'BOOKING_CONFLICT': BOOKING_CONFLICT,
    'REPAIR_INVALID': REPAIR_INVALID,
    'PACKAGE_NOT_FOUND': PACKAGE_NOT_FOUND,
    'PACKAGE_DUPLICATE': PACKAGE_DUPLICATE,
    'PACKAGE_ALREADY_PICKED': PACKAGE_ALREADY_PICKED,
    'PACKAGE_STATUS_INVALID': PACKAGE_STATUS_INVALID,
    'INVALID_PICKUP_CODE': INVALID_PICKUP_CODE,
    'PARAM_REQUIRED': PARAM_REQUIRED,
}

# 错误码对应的默认中文提示
ERROR_MESSAGES = {
    PROPERTY_NOT_FOUND: '房源不存在',
    BOOKING_CONFLICT: '预约时间冲突',
    REPAIR_INVALID: '报修信息不完整',
    PARAM_REQUIRED: '请求参数不完整',
    PACKAGE_NOT_FOUND: '快递单号不存在，请核对单号后重试',
    PACKAGE_DUPLICATE: '该快递单号已登记，请勿重复登记',
    PACKAGE_ALREADY_PICKED: '该快递已取件，请勿重复取件',
    PACKAGE_STATUS_INVALID: '当前快递状态不允许执行此操作',
    INVALID_PICKUP_CODE: '取件凭证不匹配，无法取件',
}
